# Generated by Django 4.2.3 on 2023-07-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commenters', to='reddit.comment'),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='submissions',
            field=models.ManyToManyField(blank=True, related_name='submitters', to='reddit.submission'),
        ),
    ]
