# Generated by Django 4.2.3 on 2023-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_author_submission_comments_and_more'),
        ('users', '0002_reddituser_comments_reddituser_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='submissions',
            field=models.ManyToManyField(related_name='submitted_users', to='submissions.submission'),
        ),
    ]
