# Generated by Django 4.2.3 on 2023-07-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reddituser_username_alter_reddituser_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddituser',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reddituser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
