# Generated by Django 4.2.3 on 2023-07-27 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_submission_created_at_alter_submission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit.submission'),
        ),
    ]
