# Generated by Django 4.2.3 on 2023-07-25 14:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reddituser_comments_reddituser_submissions'),
        ('comments', '0002_alter_comment_user'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(
                default=None,  # We'll set a one-off default later during data migration
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submitted_submissions',
                to='users.reddituser',
            ),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments',
            field=models.ManyToManyField(
                related_name='submission_comments', to='comments.comment'
            ),
        ),
        migrations.CreateModel(
            name='RedditSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('submission', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reddit_submissions',
                    to='submissions.submission',
                )),
            ],
        ),
    ]
